#Example
API:
  EXCHANGE:
    INFO: "https://pro-api.coinmarketcap.com/v1/exchange/info"
    MAP: "https://pro-api.coinmarketcap.com/v1/exchange/map?listing_status=active"
    QUOTES_HISTORICAL: 'https://pro-api.coinmarketcap.com/v1/exchange/quotes/historical'

  CRYPTOCURRENCY:
    MAP: "https://pro-api.coinmarketcap.com/v1/cryptocurrency/map?listing_status=active"
    QUOTES_HISTORICAL: "https://pro-api.coinmarketcap.com/v2/cryptocurrency/quotes/historical"
    OHLCV_HISTORICAL: "https://pro-api.coinmarketcap.com/v2/cryptocurrency/ohlcv/historical"

  GLOBAL_METRIC:
    QUOTES_HISTORICAL: "https://pro-api.coinmarketcap.com/v1/global-metrics/quotes/historical"

  FIAT:
    MAP: "https://pro-api.coinmarketcap.com/v1/fiat/map"

  CONTENT:
    LATEST: "https://pro-api.coinmarketcap.com/v1/content/latest"
    POST_TOP: "https://pro-api.coinmarketcap.com/v1/content/posts/top"
    POST_LATEST: "https://pro-api.coinmarketcap.com/v1/content/posts/latest"
    POST_COMMENT: "https://pro-api.coinmarketcap.com/v1/content/posts/comments"

#include the path
PATH:
  RAW_ZONE: 'D:\data_crypto\raw_zone'
  GOLDEN_ZONE: '/Users/vuh/Documents/crypto-data-engineering-project/golden_zone'

#Default date for testing
DATE: '20231107'

