#Example
API:
  EXCHANGE:
    INFO: "https://pro-api.coinmarketcap.com/v1/exchange/info"
    MAP: "https://pro-api.coinmarketcap.com/v1/exchange/map?listing_status=active"
    QUOTES_HISTORICAL: 'https://pro-api.coinmarketcap.com/v1/exchange/quotes/historical'

  CRYPTOCURRENCY:
    MAP: "https://pro-api.coinmarketcap.com/v1/cryptocurrency/map?listing_status=active"
    QUOTES_HISTORICAL: "https://pro-api.coinmarketcap.com/v2/cryptocurrency/quotes/historical"
    OHLCV_HISTORICAL: "https://pro-api.coinmarketcap.com/v2/cryptocurrency/ohlcv/historical"

  GLOBAL_METRIC:
    QUOTES_HISTORICAL: "https://pro-api.coinmarketcap.com/v1/global-metrics/quotes/historical"
  FIAT:
    MAP: "https://pro-api.coinmarketcap.com/v1/fiat/map"

#include the path
PATH:
  RAW_ZONE: '/Users/birajghimire/Desktop/crypto-data-engineering-project'
  GOLDEN_ZONE: 'Your Path'

#Default date for testing
DATE: '20231107'

